version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: divya
      POSTGRES_PASSWORD: "2305"
      POSTGRES_DB: grocery_delivery
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Django Backend Service
  backend:
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
