export const tips = [
  "Did you know? Taking regular breaks improves productivity.",
  "Stay hydrated! Drink water regularly throughout the day.",
  "Deep breathing can help reduce stress and anxiety.",
  "Try the 20-20-20 rule: Look 20 feet away every 20 minutes for 20 seconds.",
  "Regular exercise boosts both physical and mental health.",
  "A good night's sleep is crucial for memory consolidation.",
  "Practice mindfulness to stay focused and reduce stress.",
  "Organize your workspace for better productivity.",
  "Take short walks to boost creativity and energy.",
  "Use the Pomodoro Technique for better time management.",
  "Stretch regularly to prevent muscle tension.",
  "Practice gratitude daily for better mental well-being.",
  "Learn something new every day to keep your mind sharp.",
  "Good posture helps prevent back pain and fatigue.",
  "Take time to disconnect from digital devices.",
  "Healthy snacks can help maintain energy levels.",
  "Listen to calming music to reduce stress.",
  "Set clear goals to stay motivated and focused.",
  "Remember to blink often when using screens.",
  "Stay connected with friends and family.",
  "Natural light can improve mood and productivity.",
  "Regular breaks help prevent decision fatigue.",
  "Practice active listening in conversations.",
  "Celebrate small wins throughout the day.",
  "Write down your thoughts to clear your mind.",
  "Try new perspectives when solving problems.",
  "Maintain a consistent daily routine.",
  "Small progress is still progress.",
  "Your best is always good enough.",
  "Remember to smile - it boosts your mood!",
];
