# Generated by Django 5.1.4 on 2024-12-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_account_provider_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
