# Generated by Django 5.1.4 on 2025-01-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_area_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
